apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-pipelines-operator
  annotations:
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: openshift-cluster/keights-org-dev/service-operators/ocp-pipelines-operator/base
    repoURL: https://github.com/salanisor/ocp-argocd.git
    targetRevision: test
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
