apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controlplane-development
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: ./openshift-cluster/keights-org-dev/service-mesh/service-mesh-controlplane/development
    repoURL: https://github.com/salanisor/ocp-argocd.git
    targetRevision: test
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
