apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: worker1-patch
  namespace: resource-locker-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccountRef:
    name: resource-locker-node-sa
  patches:
  - targetObjectRef:
      apiVersion: v1
      kind: Node
      name: worker1.ocp4.keights.org
    patchTemplate: |
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
          node-role.kubernetes.io/infra: ""
    patchType: application/strategic-merge-patch+json
    id: worker1-node-labels
