apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - namespace.yaml
  - ./openshift-cluster/keights-org-dev/service-mesh/service-mesh-controlplane/base/servicemeshcontrolplane.yaml
