apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec: {}
