apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      retention: 48h
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          resources:
            requests:
              storage: 10Gi
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          resources:
            requests:
              storage: 2Gi
